language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      install:
        - npm install
      script:
        - npm run test:ci
    - stage: deploy
      if: (branch = master) AND (NOT (type IN (pull_request)))
      install:
        - npm install
      script:
        - npm run build:doc
      after_script:
        - cd site
        - git init
        - echo 'taro-ui.aotu.io' > CNAME
        - git add .
        - git commit -m "Update Document"
        - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
    - GH_REF: github.com/NervJS/taro-ui.git
